site_name: LaHIM
site_url: https://hospitalrun.io
site_description: LaHIM project documentation
site_author: LaHIM Core Team

repo_url: https://github.com/hospitalrun/hospitalrun-frontend/

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
