import React, { useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Button, Panel, Container, Row, Column, Spinner, Alert } from '@hospitalrun/components'
import { useWorklist } from '../../hooks/useWorklists'
import useTitle from '../../page-header/useTitle'
import useAddBreadcrumbs from '../../breadcrumbs/useAddBreadcrumbs'
import { useButtonToolbarSetter } from '../../page-header/ButtonBarProvider'

const ViewWorklist = () => {
  const { t } = useTranslation()
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { data: worklist, isLoading, error } = useWorklist(id)
  const setButtonToolBar = useButtonToolbarSetter()

  useTitle(worklist ? `${String(t('lims.worklists.view', 'View Worklist'))} - ${worklist.worklistNumber || id}` : t('lims.worklists.view', 'View Worklist'))

  useAddBreadcrumbs(
    id
      ? [
          { i18nKey: 'lims.worklists.label', location: '/lims/worklists' },
          { i18nKey: 'lims.worklists.view', location: `/lims/worklists/${id}` },
        ]
      : [],
    true
  )

  useEffect(() => {
    setButtonToolBar([
      <Button
        key="backButton"
        outlined
        color="secondary"
        icon="left-arrow"
        iconLocation="left"
        onClick={() => navigate('/lims/worklists')}
      >
        {String(t('actions.back', 'Back'))}
      </Button>,
    ])

    return () => {
      setButtonToolBar([])
    }
  }, [setButtonToolBar, navigate, t])

  if (isLoading) {
    return <Spinner color="blue" loading size={[10, 25]} type="ScaleLoader" />
  }

  if (error || !worklist) {
    return (
      <Container>
        <Alert color="danger" title={String(t('states.error', 'Error'))} message={String(error?.message || t('lims.worklists.notFound', 'Worklist not found'))} />
      </Container>
    )
  }

  return (
    <Container>
      <Panel title={`${String(t('lims.worklists.view', 'View Worklist'))} - ${worklist.worklistNumber || id}`}>
          <Row>
            <Column md={6}>
              <h4>{String(t('lims.worklists.worklistInformation', 'Worklist Information'))}</h4>
              <table className="table">
                <tbody>
                  <tr>
                    <td><strong>{String(t('lims.worklists.worklistNumber', 'Worklist Number'))}</strong></td>
                    <td>{worklist.worklistNumber || '-'}</td>
                  </tr>
                  <tr>
                    <td><strong>{String(t('lims.worklists.section', 'Section'))}</strong></td>
                    <td>{worklist.section || '-'}</td>
                  </tr>
                  <tr>
                    <td><strong>{String(t('lims.worklists.status', 'Status'))}</strong></td>
                    <td>
                      <span className={`badge badge-${worklist.status === 'completed' ? 'success' : 'warning'}`}>
                        {worklist.status || '-'}
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <td><strong>{String(t('lims.worklists.generatedDate', 'Generated Date'))}</strong></td>
                    <td>{worklist.generatedDate ? new Date(worklist.generatedDate).toLocaleString() : '-'}</td>
                  </tr>
                  <tr>
                    <td><strong>{String(t('lims.worklists.generatedBy', 'Generated By'))}</strong></td>
                    <td>{worklist.generatedBy || '-'}</td>
                  </tr>
                </tbody>
              </table>
            </Column>
            <Column md={6}>
              <h4>{String(t('lims.worklists.items', 'Worklist Items'))}</h4>
              {worklist.items && worklist.items.length > 0 ? (
                <table className="table">
                  <thead>
                    <tr>
                      <th>{String(t('lims.worklists.testName', 'Test Name'))}</th>
                      <th>{String(t('lims.worklists.accessionNumber', 'Accession Number'))}</th>
                      <th>{String(t('lims.worklists.patientName', 'Patient Name'))}</th>
                      <th>{String(t('lims.worklists.status', 'Status'))}</th>
                      <th>{String(t('actions.actions', 'Actions'))}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {worklist.items.map((item, index) => (
                      <tr key={item.id || index}>
                        <td>{item.testName || item.testCode || '-'}</td>
                        <td>{item.accessionNumber || '-'}</td>
                        <td>{item.patientName || '-'}</td>
                        <td>
                          <span className={`badge badge-${item.status === 'completed' ? 'success' : 'warning'}`}>
                            {item.status || '-'}
                          </span>
                        </td>
                        <td>
                          {item.status !== 'completed' && (
                            <Button
                              size="small"
                              color="primary"
                              icon="edit"
                              iconLocation="left"
                              onClick={() => {
                                const params = new URLSearchParams()
                                if (item.testCode) params.set('testCode', item.testCode)
                                if (item.patientId) params.set('patientId', item.patientId)
                                if (item.specimenId) params.set('specimenId', item.specimenId)
                                if (item.orderId) params.set('orderId', item.orderId)
                                navigate(`/lims/results/enter?${params.toString()}&worklistId=${id}`)
                              }}
                            >
                              {String(t('lims.worklists.enterResult', 'Enter Result'))}
                            </Button>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              ) : (
                <p>{String(t('lims.worklists.noItems', 'No items in this worklist'))}</p>
              )}
            </Column>
          </Row>
        </Panel>
    </Container>
  )
}

export default ViewWorklist

